name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 3.110.214.18
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app
          git pull origin main

          # Kill old process safely
          pkill -f "python3 app.py" || true

          sleep 2

          # Start app (fully detached)
          nohup python3 app.py > output.log 2>&1 < /dev/null &

          echo "Deployment successful"
          exit 0
